image: registry.gitlab.com/vpnbeast/docker-images/android-base:latest

variables:
  BUILD_TYPE: "assembleProdRelease"
  RELEASE_TYPE: "appDistributionUploadProdRelease"

before_script:
  - cp -f /opt/vpnbeast-android-6f673-7a6b9c6253df.json /opt/google-services.json /opt/private_key.pepk /opt/keystore.properties app/.
  - chmod +x scripts/build.sh

stages:
  - test
  - release

lint:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:lintProdDebug -PbuildDir=lint
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testProdDebug
  only:
    - master

release:
  stage: release
  script:
    - bash scripts/build.sh $BUILD_TYPE $RELEASE_TYPE
  artifacts:
    paths:
      - app/build/outputs/
  only:
    - master

# TODO: Run test and lint while merging to master. Fail if test and lint fails.
# TODO: Use files for testers and releaseNotes while uploading to Firebase App Distribution
# TODO: Take assembleProdRelease and appDistributionUploadProdRelease
# TODO: You may need a separate .gitlab-ci.yml to accomplish these