---

name: PR
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -Pci --console=plain :app:lintProdDebug -PbuildDir=lint
          gradle-executable: ./gradlew

  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -Pci --console=plain :app:testProdDebug
          gradle-executable: ./gradlew
